### ISSUE TITLE
Raid Chat and Contact Method Table - Updated

### ISSUE THREAD

**Issue by billythakidd04** [rbaia28/mew.co#5]
- Facebook messenger
- discord
- WhatsApp 
- Instagram
- Signal
- email 
- sms/imessage 
- potential FB group integration but unsure if every city has an active group

**Comment by billythakidd04** [comment]
@rbaia28 please edit the description and fill out any other options (or delete any that don't make sense)

**Comment by billythakidd04** [comment]
@rbaia28 why the hell is this closed?!?! :laughing:

**Comment by rbaia28** [comment]
because i am a spaz!!!!!!!!!!!!
